upstream django_upstream {
    server web:8000;
}

server {
    include mime.types;
    default_type application/octet-stream;
    listen 80;
    server_name trip-pulse.uz www.trip-pulse.uz;

    client_max_body_size 20M;

    location /static/ {
        alias /vol/static/;
        expires 7d;
    }

    location /media/ {
        alias /vol/media/;
        expires 7d;
    }

    location / {
        proxy_pass http://django_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}